### ISSUE TITLE
Is there a way to turn off debug output?

### ISSUE THREAD

**Issue by ghost** [nbarthel/cryptsy-api#1]
I don't see a way to turn off the debug output. I have forked the repo I can add this and send a pull request if you are interested?

**Comment by nbarthel** [comment]
Good question.  This is a fork, I'm still working through the code myself.

**Comment by nbarthel** [comment]
Nevermind... I'm silly.  This is my code.  It's a first stab, pull requests are certainly welcome.  I'll probably rewrite it as the first run of code stinks.

**Comment by nbarthel** [comment]
I removed the debug $stderr from the private methods and bumped the version.

**Comment by ghost** [comment]
Hey Nic, Thanks for removing the debug. Cryptsy seems to be picking up
speed, what do you think of the site so far?

I was looking at making some additions, should I wait for your rewrite?

On Fri, Nov 29, 2013 at 3:39 AM, Nic Barthelemy notifications@github.comwrote:

> I removed the debug $stderr from the private methods and bumped the
> version.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nbarthel/cryptsy-api/issues/1#issuecomment-29502533
> .

## 

CR

**Comment by nbarthel** [comment]
I'd say feel free to push code.  We can work together on refactoring things as they develop.  Open to a collaboration?
