### ISSUE TITLE
JSON Parser Error

### ISSUE THREAD

**Issue by JsonSam** [nbarthel/cryptsy-api#14]
In gem there is no handling of JSON parser error. 

A JSON::ParserError occurred in background at 2014-11-10 07:12:12 UTC :
  </style>

  <script>
    var toggle = function(id) {
      var s = document.getElementById(id).style;
      s.display = s.display == 'none' ? 'block' : 'none';
      return false;
    }
    var show = function(id) {
      document.getElementById(id).style.display = 'block';
    }
    var hide = function(id) {
      document.getElementById(id).style.display = 'none';
    }
    var toggleTrace = function() {
      return toggle('blame_trace');
    }
    var toggleSessionDump = function() {
      return toggle('session_dump');
    }
    var toggleEnvDump = function() {
      return toggle('env_dump');
    }
  </script>
</head>
<body>

<header>
  <h1>
    JSON::ParserError
  </h1>
</header>
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call&#39;
rack (1.5.2) lib/rack/head.rb:11:in`call&#39;
actionpack (4.1.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call&#39;
actionpack (4.1.6) lib/action_dispatch/middleware/flash.rb:254:in`call&#39;
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context&#39;
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in`call&#39;
actionpack (4.1.6) lib/action_dispatch/middleware/cookies.rb:560:in `call&#39;
actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:29:in`block in call&#39;
activesupport (4.1.6) lib/active_support/callbacks.rb:82:in `run_callbacks&#39;
actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in`call&#39;
actionpack (4.1.6) lib/action_dispatch/middleware/reloader.rb:73:in `call&#39;
actionpack (4.1.6) lib/action_dispatch/middleware/remote_ip.rb:76:in`call&#39;
actionpack (4.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call&#39;
actionpack (4.1.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call&#39;
railties (4.1.6) lib/rails/rack/logger.rb:38:in `call_app&#39;
railties (4.1.6) lib/rails/rack/logger.rb:20:in`block in call&#39;
activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `block in tagged&#39;
activesupport (4.1.6) lib/active_support/tagged_logging.rb:26:in`tagged&#39;
activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `tagged&#39;
railties (4.1.6) lib/rails/rack/logger.rb:20:in`call&#39;
actionpack (4.1.6) lib/action_dispatch/middleware/request_id.rb:21:in `call&#39;
rack (1.5.2) lib/rack/methodoverride.rb:21:in`call&#39;
rack-contrib (1.1.0) lib/rack/contrib/runtime.rb:18:in `call&#39;
activesupport (4.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in`call&#39;
rack (1.5.2) lib/rack/lock.rb:17:in `call&#39;
actionpack (4.1.6) lib/action_dispatch/middleware/static.rb:64:in`call&#39;
rack-contrib (1.1.0) lib/rack/contrib/sendfile.rb:105:in `call&#39;
railties (4.1.6) lib/rails/engine.rb:514:in`call&#39;
railties (4.1.6) lib/rails/application.rb:144:in `call&#39;
/home/ubuntu/.rvm/gems/ruby-2.1.3@yb-service-stag/gems/passenger-4.0.50/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in`process_request&#39;
/home/ubuntu/.rvm/gems/ruby-2.1.3@abc/gems/passenger-4.0.50/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request&#39;
/home/ubuntu/.rvm/gems/ruby-2.1.3@abc/gems/passenger-4.0.50/lib/phusion_passenger/request_handler/thread_handler.rb:109:in`main_loop&#39;
/home/ubuntu/.rvm/gems/ruby-2.1.3@abc/gems/passenger-4.0.50/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads&#39;</code></pre>
    </div>
    <div id="Full-Trace" style="display: none;">
      <pre><code>/home/ubuntu/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/json/common.rb:155:in`parse&#39;
/home/ubuntu/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/json/common.rb:155:in `parse&#39;
cryptsy-api (0.1.4) lib/cryptsy/api.rb:42:in`execute_method&#39;
cryptsy-api (0.1.4) lib/cryptsy/api.rb:204:in `call_private_api&#39;
cryptsy-api (0.1.4) lib/cryptsy/api.rb:82:in`getinfo&#39;

**Comment by nbarthel** [comment]
Yes, this gem was pretty sparse in terms of validation and testing.  I'll see about adding some better support...
