### ISSUE TITLE
addressing the security note about cookies on the api page of cryptsy.com?

### ISSUE THREAD

**Issue by hayksaakian** [nbarthel/cryptsy-api#3]
Via 
https://www.cryptsy.com/pages/api

> Security Note: Since implementation of our new security layer, some API clients are getting denied access. If possible, you should program your bot to accept cookies to pass the security test. If you are still unable to connect, then contact us with your IP address so that we may whitelist your application. 

Correct me if im wrong, but browsing over the code, it seems like you create a new user agent on every request, so at a glance it seems like cookies don't persist between calls.

Is that something you were going to address? I wouldn't want to contact cryptsy each time my IP address changes.

**Comment by hayksaakian** [comment]
If I come up with a solution I'll submit a pull request

**Comment by nbarthel** [comment]
Thanks again for the patch.  I'm pushing out a new version of the gem now to Rubygems.
